### ISSUE TITLE
请问应该如何运行

### ISSUE THREAD

**Issue by clt85046** [shangwen/SparkOpenFalconSink#1]
你好，请问可否告知该如何使用该工具？

**Comment by shangwen** [comment]
编译之后--jar一起提交，还要配置metrics.properties配置上对应的类，streaming的数据就会发送到openfalcon上面了，同时你可以指定app的的metric前缀的名字，这样同一个app的数据都会汇聚到一个dashboard上面，否则则以applicationId作为前缀

**Comment by shangwen** [comment]
这个参数spark.metrics.namespace=your-job-name

**Comment by clt85046** [comment]
十分感谢！请问配置metrics.properties是这样的吗？
![image](https://user-images.githubusercontent.com/32003064/39513527-3f508ed2-4e27-11e8-81dd-88a17fa97412.png)
还有请问提交jar的语句是什么样的，方便的话可否给一个大致样例参考一下，谢谢
